
name: BikeDrivers Frontend Application Deployment

on:
  push:
    branches: [ "main", "testDeployment" ]
  pull_request:
    branches: [ "main", "testDeployment" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Connexion à DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build de l'image docker contenant le contenu du dépôt
        run: | 
          docker image build -t ${{ secrets.DOCKER_USER }}/bikedrivers-frontend:v1-${{ github.sha }} .
          docker image push ${{ secrets.DOCKER_USER }}/bikedrivers-frontend:v1-${{ github.sha }}