name: React Vite Frontend Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.18

      # Defining the cache dir in the environment variables of the runner
      - name: Set Up Cache
        run: echo "NODE_CACHE_DIR=$(npm config get cache)" >> $GITHUB_ENV

      # Defining the cache dir access options
      - name: Caching Dependencies
        uses: actions/cache@v4
        with:
          path: ${{ env.NODE_CACHE_DIR }}
          key: react-vite-{{ hashFiles('**/frontend/package.json') }}
          restore-keys: |
            react-vite-latest-

      - name: Install dependencies
        run: npm install

      # Executing tests
      - name: Running tests
        run: npm run test > /tmp/tests-result.txt

      - name: Upload security audit report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: tests-results
          path: /tmp/tests-result.txt